spring.application.name=sb-ecom
spring.cache.type=redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}



#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test


#Postgres Sql

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cisco@123}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
#spring.jpa.database-platform=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

project.image=images/

spring.app.jwtSecret=mySecretKey912738cascasvfsdafvsduhfasdufhSDUFHDASDFVSDA
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}
spring.ecom.app.jwtCookieName=springBootEcom

frontend.url=http://localhost:5173
image.base.url=http://localhost:8080/images



#Stripe KEY
stripe.secret.key=${STRIPE_SECRET_KEY:}




#Semantic product search
app.search.semantic.enabled=${APP_SEARCH_SEMANTIC_ENABLED:false}
app.search.semantic.top-k=${APP_SEARCH_SEMANTIC_TOP_K:20}
app.search.semantic.similarity-threshold=${APP_SEARCH_SEMANTIC_SIMILARITY_THRESHOLD:0.50}
spring.ai.model.embedding=${SPRING_AI_MODEL_EMBEDDING:none}
spring.ai.vectorstore.type=${SPRING_AI_VECTORSTORE_TYPE:none}
spring.ai.model.chat=${SPRING_AI_MODEL_CHAT:none}
spring.ai.model.image=${SPRING_AI_MODEL_IMAGE:none}
spring.ai.model.moderation=${SPRING_AI_MODEL_MODERATION:none}
spring.ai.model.chat.audio.speech=${SPRING_AI_MODEL_AUDIO_SPEECH:none}
spring.ai.model.chat.audio.transcription=${SPRING_AI_MODEL_AUDIO_TRANSCRIPTION:none}
#spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key-not-used}
spring.ai.openai.embedding.option.model=text-embedding-3-small
spring.ai.vectorstore.pgvector.initialize-schema=${SPRING_AI_VECTORSTORE_PGVECTOR_INITIALIZE_SCHEMA:true}
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.table-name=product_vector_store
spring.ai.openai.audio.speech.enabled=false
#force data.sql to run
spring.sql.init.mode=always

#waits for Hibernate to create the tables before running the script
spring.jpa.defer-datasource-initialization=true

#GitHub OAuth2 configuration
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}